import './globals.css';
import 'antd/dist/reset.css'; 
import type { Metadata } from 'next';
import { Inter } from "next/font/google";
import Providers from '@/redux/provider';
import { GoogleOAuthProvider } from '@react-oauth/google';
import ToastProvider from '@/components/toast/ToastProvider';
import AppHeader from '@/components/header/Header';
import AppFooter from '@/components/footer/Footer';
export const metadata: Metadata = {
  title: 'Booking Hotels App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}>
          <Providers>
            <AppHeader/>
              {children}
            <AppFooter/>
          </Providers>
        </GoogleOAuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
